name: 'JReleaser'
description: 'Run JReleaser to create GitHub release, deploy to Maven Central, and send notifications'

inputs:
  version:
    description: 'Project version'
    required: true
  git-access-token:
    description: 'GitHub token for creating release'
    required: true
  gpg-secret-key:
    description: 'GPG secret key for signing'
    required: false
  gpg-public-key:
    description: 'GPG public key'
    required: false
  gpg-passphrase:
    description: 'GPG passphrase'
    required: false
  sonatype-username:
    description: 'Sonatype username'
    required: false
  sonatype-password:
    description: 'Sonatype password'
    required: false
  slack-webhook:
    description: 'Slack webhook URL'
    required: false
  skip-announce:
    description: 'Skip announcements (sets JRELEASER_ANNOUNCE_SLACK_ACTIVE to NEVER)'
    required: false
    default: 'false'
  docker-username:
    description: 'Docker registry username'
    required: false
  docker-password:
    description: 'Docker registry password'
    required: false
  jreleaser-version:
    description: 'JReleaser version'
    required: false
    default: 'latest'
  arguments:
    description: 'JReleaser arguments'
    required: false
    default: 'full-release'
  artifact-name-suffix:
    description: 'Suffix for artifact name to avoid conflicts when called multiple times'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Release with JReleaser
      uses: jreleaser/release-action@v2
      with:
        arguments: ${{ inputs.arguments }}
        version: ${{ inputs.jreleaser-version }}
      env:
        JRELEASER_GITHUB_TOKEN: ${{ inputs.git-access-token }}
        JRELEASER_GPG_PASSPHRASE: ${{ inputs.gpg-passphrase }}
        JRELEASER_GPG_PUBLIC_KEY: ${{ inputs.gpg-public-key }}
        JRELEASER_GPG_SECRET_KEY: ${{ inputs.gpg-secret-key }}
        JRELEASER_MAVENCENTRAL_USERNAME: ${{ inputs.sonatype-username }}
        JRELEASER_MAVENCENTRAL_PASSWORD: ${{ inputs.sonatype-password }}
        JRELEASER_SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
        JRELEASER_ANNOUNCE_SLACK_ACTIVE: ${{ inputs.skip-announce == 'true' && 'NEVER' || '' }}
        JRELEASER_DOCKER_DEFAULT_USERNAME: ${{ inputs.docker-username }}
        JRELEASER_DOCKER_DEFAULT_PASSWORD: ${{ inputs.docker-password }}
        JRELEASER_PROJECT_VERSION: ${{ inputs.version }}

    - name: Upload JReleaser Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: jreleaser-logs${{ inputs.artifact-name-suffix }}
        path: |
          out/jreleaser/trace.log
          out/jreleaser/output.properties
