name: 'Create Release Tag'
description: 'Create a release tag using Axion Release Plugin'

inputs:
  version:
    description: 'Specific version to release (optional)'
    required: false
  version-increment:
    description: 'Version increment type (major, minor, patch)'
    required: false
    default: 'patch'
  git-access-token:
    description: 'GitHub token for pushing tags'
    required: true
  working-directory:
    description: 'Working directory for Gradle commands'
    required: false
    default: '.'
  tag-prefix:
    description: 'Tag prefix (e.g., "v", "java-client-v")'
    required: false
    default: 'v'

outputs:
  version:
    description: 'The version that was released'
    value: ${{ steps.create_tag.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Configure Git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Create Release Tag
      id: create_tag
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        GITHUB_TOKEN: ${{ inputs.git-access-token }}
        TAG_PREFIX: ${{ inputs.tag-prefix }}
      run: |
        if [ -n "${{ inputs.version }}" ]; then
          ./gradlew release -Prelease.version=${{ inputs.version }} -Prelease.tagPrefix="${TAG_PREFIX}" -Prelease.disableChecks
        else
          # Capitalize first letter of version-increment (patch -> Patch, minor -> Minor, major -> Major)
          INCREMENT="${{ inputs.version-increment }}"
          INCREMENT_CAPITALIZED="$(tr '[:lower:]' '[:upper:]' <<< ${INCREMENT:0:1})${INCREMENT:1}"
          ./gradlew release -Prelease.versionIncrementer=increment${INCREMENT_CAPITALIZED} -Prelease.tagPrefix="${TAG_PREFIX}" -Prelease.disableChecks
        fi

        # Get the version that was just tagged
        VERSION=$(./gradlew currentVersion -q | grep "Project version:" | cut -d' ' -f3)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Released version: $VERSION"

    - name: Checkout Release Tag
      shell: bash
      env:
        RELEASE_VERSION: ${{ steps.create_tag.outputs.version }}
        TAG_PREFIX: ${{ inputs.tag-prefix }}
      run: |
        git fetch --tags
        git checkout "${TAG_PREFIX}${RELEASE_VERSION}"
