name: 'Test Reporter'
description: 'Wrapper around dorny/test-reporter to centralize the pinned version'

inputs:
  name:
    description: 'Check run name.'
    required: true
  path:
    description: 'Glob that matches test report files.'
    required: true
  reporter:
    description: 'Test report format.'
    required: true
  fail-on-error:
    description: 'Whether to fail the workflow if reporting fails.'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Publish test report
      uses: dorny/test-reporter@v3.0.0
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        reporter: ${{ inputs.reporter }}
        fail-on-error: ${{ inputs.fail-on-error }}
